<?php
/**
 * Plugin Name:       Card Flip to Modal
 * Description:       A Gutenberg block that opens custom card content in a modal.
 * Version:           0.1.0
 * Requires at least: 6.8
 * Requires PHP:      7.4
 * Author:            Loren Nicole Simons
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       card-flip-to-modal
 *
 * @package           FunGutenbergBlocks
 */

/**if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}*/

/**
 * Registers the Card Flip to Modal block.
 *
 * WordPress 6.8 supports registering block metadata collections from
 * a blocks-manifest.php file generated by @wordpress/scripts.
 */
/**function fun_gutenberg_blocks_card_flip_to_modal_block_init() {
	if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) ) {
		wp_register_block_types_from_metadata_collection(
			__DIR__ . '/build',
			__DIR__ . '/build/blocks-manifest.php'
		);

		return;
	}*/

	// Fallback for older WordPress versions or builds without a manifest.
	/**register_block_type( __DIR__ . '/build' );
}
add_action( 'init', 'fun_gutenberg_blocks_card_flip_to_modal_block_init' );*/


/**
 * Plugin Name:       Card Flip to Modal
 * Description:       A Gutenberg block that opens custom card content in a modal.
 * Version:           0.1.0
 * Requires at least: 6.1
 * Requires PHP:      7.4
 * Author:            Loren Nicole Simons
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       card-flip-to-modal
 *
 * @package           FunGutenbergBlocks
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the Card Flip to Modal block.
 */
function fun_gutenberg_blocks_card_flip_to_modal_block_init() {
	register_block_type( __DIR__ . '/build' );
}
add_action( 'init', 'fun_gutenberg_blocks_card_flip_to_modal_block_init' );
